version: '3'

services:
  app:
    build: .
    container_name: node
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c "npm start"
    ports: 
      - "3000:3000"
    tty: true